### ISSUE TITLE
TypeError: n is undefined

### ISSUE THREAD

**Issue by GrosSacASac** [arturkot/the-house-game#3]
Tried here http://the-house.arturkot.pl/ on Firefox v52

TypeError: n is undefinedroom-min.js:2:3711
	room.grid/add_collisions http://the-house.arturkot.pl/js/min/room-min.js:2:3711
	room.grid http://the-house.arturkot.pl/js/min/room-min.js:2:3736
	room.the_player.go_to.start http://the-house.arturkot.pl/js/min/room-min.js:2:6036
	scene.explosion http://the-house.arturkot.pl/js/min/scenes-min.js:1:9960
	view.start/g/</</<

I went downstairs in the dark, and later I looked at the window in the bathroom and when I stopped looking outside the window, the game froze, sound continue playing.

**Comment by arturkot** [comment]
Here goes a super quick reply. ;) Thanks for the report! I'll look into that (not sure when exactly...) and see what can be done.

**Comment by arturkot** [comment]
Hi @GrosSacASac ,

I've _attempted_ to fix the error you've reported despite the fact I couldn't reproduce it. Some notes:

* I think it happened mainly because code quality in the game is just _low_. Weird things all over the place.
* This is more of a monkey patch... 
* To really fix this issue (and ton of other ones...) I believe I'd have to rewrite the whole thing from scratch. Perhaps using the original assets and replacing the whole codebase OR adding _new_ 3d graphics, some _new_ puzzles, gameplay adjustments, and additional ending. The latter would be basically a remake.

Cheers,

Artur
